### ISSUE TITLE
Wrong temperatures in tos (Omon)

### ISSUE THREAD

**Issue by zklaus** [EC-Earth/ece2cmor3#296] opened 2018-10-22 13:00 UTC
The tos reports temperatures of ~ -270 degC for the sea surface temperature.
It also gives original_units K, so it seems like the original data was already in degC, but was interpreted to be in K and then converted again to degC.

**Comment by goord** [comment] 2018-10-22 13:19
Hi @zklaus , which data are you looking at? I just checked my ocean output which is fine. I think this issue only occurs when tos is derived from the atmospheric model.  @oloapinivad I just looked at our 3-hourly for primavera tos and it suffers from the same bug

**Comment by oloapinivad** [comment] 2018-10-22 13:42
I can confirm this occurs only for the tos derived from IFS: files on gn grid are Celcius, files on gr grid are in K. 

Actually, having tos in Oday, Omon and 3hr gave me 5 files for tos:
```
tos_3hr_EC-Earth3P-HR_control-1950_r1i1p2f1_gr_195001010000-195012312100.nc  
tos_Omon_EC-Earth3P-HR_control-1950_r1i1p2f1_gn_195001-195012.nc
tos_Oday_EC-Earth3P-HR_control-1950_r1i1p2f1_gn_19500101-19501231.nc         
tos_Omon_EC-Earth3P-HR_control-1950_r1i1p2f1_gr_195001-195012.nc
tos_Oday_EC-Earth3P-HR_control-1950_r1i1p2f1_gr_19500101-19501231.nc
```

More in general, we need to decide if tos is derived from NEMO or from IFS (see issue #231 ). This half-half approach is a bit unstable.

**Comment by zklaus** [comment] 2018-10-23 08:19
Hi, sorry for the delay, yesterday I had some computer problems.
I got the data I am talking about from @treerink for the cmip6 step-by-step presentation at the EC-Earth meeting. It was in a file called cmor-t143-001-CMIP-piControl.tar.gz coming from application of ece2cmor for a (test) CMIP6 piControl run.

If this was derived from the atmosphere it would be rather strange: It comes on a NEMO ocean grid and lives in Omon after all.

**Comment by goord** [comment] 2018-11-05 09:31
@zklaus can you verify that the original model output has the correct unit degC and correct values? Just to make sure that the input of ece2cmor3 is correct...

**Comment by zklaus** [comment] 2018-11-06 13:51
Will do. Right now I am waiting for a newer run to finish. I will let you know one I know.

**Comment by zklaus** [comment] 2018-11-07 09:09
@goord I can confirm that actually the nemo output is already broken and contains units of `K` instead of `degC` for `tos` with values between -2 and 32. I'll comment here once I know the fix.

**Comment by zklaus** [comment] 2018-11-07 10:13
@treerink: It seems this is an error in `file_def_nemo-opa.xml`. There, tos claims units of `K`, but the data is in `degC`, which is the correct unit according to the cmip tables.

**Comment by treerink** [comment] 2018-11-07 11:01
In order to obtain immediately literary the correct cmor unit name (otherwise cmor aborts when cmorising) in the `file_def` files I take the unit form the data request, but not before an automatic check that this cmor unit equals indeed the (not always literary) unit in the ping file. So in fact the unit from the ping file is taken, I checked this is also the case for `tos`. 

However by further inspecting the ping file comment just now, it appears that also in this comment the unit is questioned (see code below). All with all it looks like the correct expression to convert from Celsius to Kelvin is missing in the ping file. 

The `tos` line in the ocean ping file (1st line Shaconemo revision 256, 2nd line Shaconemo revision 273 ):
`````
Shaconemo r256:   <field id="CMIP6_tos"  field_ref="sst_pot" /> <!-- P1 (K)    sea_surface_temperature : temperature of liquid ocean.  Note that the correct standard_name for this variable is "sea_surface_temperature", not "surface_temperature", but this was discovered too late to correct.  To maintain consistency across CMIP5 models, the wrong standard_name will continue to be used. **** NEMO-RD: TODO : JM: is this really requested in K? This does not agree with the .xls document. To be clarified. In NEMO, sst given in Celsius -->
Shaconemo r273:   <field id="CMIP6_tos"  field_ref="sst_pot" /> <!-- P1 (degC) sea_surface_temperature : temperature of liquid ocean.  Note that the correct standard_name for this variable is "sea_surface_temperature", not "surface_temperature", but this was discovered too late to correct.  To maintain consistency across CMIP5 models, the wrong standard_name will continue to be used. **** NEMO-RD: TODO : JM: is this really requested in K? This does not agree with the .xls document. To be clarified. In NEMO, sst given in Celsius -->
`````
After including the second line with Shaconemo revision 273 (the one based on Data Request 01.00.27, in this revision they have now more variants), we can see they adjusted the unit to degC (the questing comment remains).

Note that `genecec` and the rest of `ece2cmor3` still uses Shaconemo revision 256. The Shaconemo update for the ping files will take place as soon the EC-Earth XIOS2.5 upgrade & Shaconemo update (issues 508 & 560 at the portal) have a green light.

**Comment by zklaus** [comment] 2018-11-07 13:56
@ufladrich: Could you comment on the status of the upgrade?

**Comment by ufladrich** [comment] 2018-11-07 14:11
* the IPSL shaconemo repository is at revision 273
* our `r5859-upgrade-xios-to-2.5` branch is at revision 270
* our trunk is at revision 256

**Comment by treerink** [comment] 2018-11-07 14:31
This  `K -> degC`  change in `ping_ocean_DR1.00.27.xml`  comes from Shaconemo revision 266.

**Comment by zklaus** [comment] 2018-11-08 11:45
Thanks @treerink. So, what do you think is the way forward? Merge `r5859-upgrade-xios-to-2.5` into `r5717-cmip6-nemo-namelists` and update everything to shaconemo 270?

**Comment by treerink** [comment] 2018-11-23 13:21
Indeed after the XIOS-2.5 upgrade & the Shaconemo update to revision 274 in EC-Earth3 trunk (and by merging these into the `cmip6-nemo-namelists` branch), and after updating `genecec`/`ece2cmor3` for  Shaconemo update to revision 274 and to CMIP6 data request version 01.00.28, this issue is solved.

I used the newly generated file_def files (not yet committed in the  `cmip6-nemo-namelists` branch) which are generated by the updated `genecec` and cmorized them with the updated `ece2cmor3` version by using:
`````
 ece2cmor cmip6-ec-earth-output/t204/001/ --exp t204 --oce --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/resources/test-data-request/varlist-nemo-test.json --odir cmor-test
`````
The values of `Omon tos` are in the range of degrees Celsius temperatures.

So closing this issue.

**Closed by treerink** 2018-11-23 13:21 UTC
Labels: release 0.9
