### ISSUE TITLE
Varlists for different CMIP experiments?

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#170] opened 2018-05-18 08:18 UTC
A quick (and maybe stupid) question: how do we create the varlist.json file needed as input for ece2cmor3? Is there something similar to drq2ppt that creates the varlist based on the drq and the available variables?

**Comment by oloapinivad** [comment] 2018-05-18 08:35
I agree with Klaus. This will be very helpful.

**Comment by goord** [comment] 2018-05-18 08:45
Well there is the drq tool that produces excel files for your experiment; these can be read by ece2cmor3 instead of the varlist.json

**Comment by aearamos** [comment] 2018-05-18 09:02
Well, there is a function that do that. 

Just this week I started using the makedrq.sh from https://github.com/EC-Earth/ece2cmor3/tree/primavera/resources/data_request. It's from an older version of ece2cmor3, but it seems to be working fine. I tried with different MIPS after using the drq command and was able to generate the varlist.json files. I then compared the tables and the files seem fine.

As @goord mentioned, you won't need it anymore, but it's good to know you have that option. 

Arthur

**Comment by oloapinivad** [comment] 2018-05-18 09:11
Thanks, 
so we can use xls files, good news. Just to double-check, this will not work with PRIMAVERA data request, is it true?

Paolo

**Comment by goord** [comment] 2018-05-18 09:12
Hi @aearamos , the makedrq.sh is now adopted in ece2cmor3 itself: you can run the dreq tool to generate an excel file for your experiment and pass that one as the --varlist option to ece2cmor3; @treerink uses this functionality all the time when he is assessing the completeness of our parameter files.

**Comment by goord** [comment] 2018-05-18 09:13
@oloapinivad Euhm... not sure, the only way to know is to try

**Comment by aearamos** [comment] 2018-05-18 09:27
Hi @goord, thanks for the clarification. It makes sense to use the excel files now directly. And @oloapinivad, you can download the Primavera table and json file to try it yourself. But if the tables and json files are there it should work.

Good luck.

Arthur

**Comment by oloapinivad** [comment] 2018-05-18 09:36
Hi guys, thanks for the hints.

I have tried but apparently the PRIMAVERA data request is not in the same format...
````
/drq2ppt.py --vars PRIMAVERA_Data_Request_v01_00_07.xlsx --tabdir /marconi/home/userexternal/pdavini0/work/ecearth3/cmorization/jon-seddon-tables/ --tabid PRIMAVERA
  File "./drq2ppt.py", line 159, in <module>
    main()
  File "./drq2ppt.py", line 150, in main
    taskloader.load_targets(args.vars,load_atm_tasks = True,load_oce_tasks = False)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/taskloader.py", line 68, in load_targets
    targetlist = load_targets_excel(varlist)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/taskloader.py", line 142, in load_targets_excel
    priority_index = row.index(priority_colname)
ValueError: 'Priority' is not in list
````

**Comment by aearamos** [comment] 2018-05-18 09:54
@oloapinivad , I just triend running ./drq2ppt.py --vars ../resources/data_request/PRIMAVERA_Data_Request.xlsx  and it works fine for me. I did not choose the --tabdir option but that should'tn be a problem The ppt files were creates, but I did not check all the variables one by one.

Hope this helps.

Arthur

**Comment by oloapinivad** [comment] 2018-05-18 09:56
Hi Arthur,

from where did you downloaded the DATA request? Perhaps I have a wrong
version!
Thanks
Paolo

2018-05-18 11:54 GMT+02:00 Arthur Ramos <notifications@github.com>:

**Comment by aearamos** [comment] 2018-05-18 10:06
Well, I've just tried with the one file from https://github.com/EC-Earth/ece2cmor3/tree/primavera/resources/data_request and it works. I used the same file as you. Did you try without the -tabdir option?

**Comment by oloapinivad** [comment] 2018-05-18 10:18
Actually in this way is working, probably I was doing something wrong.
Now I have the ppts, even if I have pages of errors and missing variables.
However, there is no excel file to be passed to ece2cmor3, is this correct?
Sorry for the mess
Paolo

2018-05-18 12:06 GMT+02:00 Arthur Ramos <notifications@github.com>:

**Comment by treerink** [comment] 2018-05-18 15:13
For CMIP6 you will probably use first the `generate-ec-earth-namelists.sh` in order to create the namelists (ppt files and file_def files for nemo (the latter not yet possible)). This will also create in the background the excel file with the data request of your experiment, e.g.:
`cmip6-data-request/cmip6-data-request-m=CMIP-e=amip-t=1-p=1/cmvme_CMIP_amip_1_1.xlsx`
which can be used as the data request input file for ece2cmor3 when starting the cmorization.

For the cmorization of previous PRIMAVERA runs, the story might be slightly more complicated depending on which data request version your output is based.

**Comment by aearamos** [comment] 2018-05-18 16:13
So @treerink, regarding the nemo file_def files, is it possible to use dr2xml, or is it outdated? I've been trying to run it without much success so far, since its structure is a little different than what we have for drq and drq2ppt. I know it's a different package, but I wanted to know if someone has been using it successfully.

**Comment by treerink** [comment] 2018-05-22 10:58
@aearamos: I tried, but in the end we decided (inside the CMIP6 WG, and reported to the SG) to discontinue this effort because the `dr2xml` developers confirmed they couldn't provide any support at short term i.e. CMIP6 time scale. I have added this wiki:
https://dev.ec-earth.org/projects/cmip6/wiki/Dr2xml_issues
and this ec earth patch for dr2xml:
https://github.com/treerink/ece-dr2xml-patch
However they are not update anymore for two reasons: 1. Because issue 448 at the ec earth portal is solved so this has reduced one section of problems (see wiki) with `dr2xml.` 2. I see that (since today) after a long silence another push from the developer gives a series of commits which I have not tested.

I am currently very busy to implement our ec earth alternative: so I hope within a week time to be able to provide here the additional `dr2nemo_file_def` tool so the second component becomes available in `generate-ec-earth-namelists.sh`

**Comment by treerink** [comment] 2018-06-08 08:07
To answer the original question: Yes now there is `drq2file_def-nemo.py` and it is called by
`generate-ec-earth-namelists.sh`. So it is enough to call the latter one. Note however that #179 is blocking, in the sense that as soon #179 is solved the full list of non-dummy shaconemo ping file variables comes available. Which is now only the case if using the auto-grid-detection branch. (I will merge the last commits in the master to that branch in a second).

So closing this issue.

**Closed by treerink** 2018-06-08 08:07 UTC
Labels: question
