### ISSUE TITLE
Error when cmorizing table 6hrPlevPt

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#324] opened 2018-11-27 19:15 UTC
Hi, I found a possible error when cmorizing variables in table 6hrPlevPt:

WARNING:ece2cmor3.ifs2cmor:For variable va in table 6hrPlevPt, no valid time point could be found at 1990-01-01 00:00:00...inserting missing values
/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/CMOR-3.3.3-py2.7-linux-x86_64.egg/cmor/pywrapper.py:754: UserWarning: Error: your data shape ((3, 256, 512)) does not match the expected variable shape ([256, 512, 3, 0])
Check your variable dimensions before caling cmor_write
  warnings.warn(msg)

Whenever I check the tmp folder, the file va_6hrPlevPt.nc is correct, with the right values, axis, and dimensions, as you can see here:

 netcdf va_6hrPlevPt {
dimensions:
	lon = 512 ;
	lat = 256 ;
	plev = 3 ;
	time = UNLIMITED ; // (123 currently)
variables:
	float lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
	float lat(lat) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
	double plev(plev) ;
		plev:standard_name = "air_pressure" ;
		plev:long_name = "pressure" ;
		plev:units = "Pa" ;
		plev:positive = "down" ;
		plev:axis = "Z" ;
	double time(time) ;
		time:standard_name = "time" ;
		time:units = "hours since 1990-1-1 06:00:00" ;
		time:calendar = "proleptic_gregorian" ;
		time:axis = "T" ;
	float var132(time, plev, lat, lon) ;
		var132:table = 128 ;

// global attributes:
		:CDI = "Climate Data Interface version 1.8.2 (http://mpimet.mpg.de/cdi)" ;
		:Conventions = "CF-1.6" ;
		:history = "Tue Nov 27 19:46:17 2018: cdo -O -f nc -P 4 sp2gpl -sellevel,85000.,50000.,5000. -selzaxis,pressure -selhour,0,6,12,18 -selcode,132 /gpfs/scratch/pr1eel00/pr1eel17/a1fu/auto-ecearth3/ece2cmor/ece2cmor3/atm-fc0-199001/a1fu-ifs-1990/132.128.210.6 /gpfs/scratch/pr1eel00/pr1eel17/a1fu/auto-ecearth3/ece2cmor/ece2cmor3/atm-fc0-199001/a1fu-ifs-1990/va_6hrPlevPt.nc" ;
		:institution = "European Centre for Medium-Range Weather Forecasts" ;
		:CDO = "Climate Data Operators version 1.8.2 (http://mpimet.mpg.de/cdo)" ;
		:cdo_openmp_thread_number = 4 ;
}

The file in my cmor_output folder is allzeros. The cmorisation was working a few commits before but now it's failing, at least for me.

Edit: Strangely, this happened in my first two months (two chunks), but my third month and chunk was just fine.

Thanks
Arthur

**Comment by goord** [comment] 2018-11-28 09:46
Hi Arthur, I assume 1990-01-01 is your start date, so it makes sense ece2cmor3 has to insert missing values at the beginning to fill up the missing pressure levels. I guess you can observe in the va_6hrPlevPt.nc file that the first time stamp 1990-01-01 00:00:00 is missing. I don't understand however why the cmor library is complaining about the shape.

Could you somehow transfer the EC-Earth output to me, perhaps via the ECMWF infrastructure?

**Comment by aearamos** [comment] 2018-11-28 09:55
Hi Gijs, I can send you an email. It's only a month, so the files are not big, if that's OK for you.

**Comment by goord** [comment] 2018-11-28 09:57
Sure, if it fits in an email attachment that's fine for me.

**Comment by aearamos** [comment] 2018-11-28 09:58
Nevermind, it doesn't fit in an email attachment. I'll send you the file via ftp from our system.

**Comment by goord** [comment] 2018-11-29 08:34
Hi Arthur, on my system I also get he warning from CMOR but the processing works, I get values for time steps > 0 as expected, have you checked all time steps in your output files?

**Comment by aearamos** [comment] 2018-11-29 14:56
Hi Gijs, silly me. I checked now the other timesteps and they work. I guess since I open the files just to check if they're OK and close them without doing a proper check, I never noticed the other steps. I'll reopen the issue if the problem persists. 

Thanks again!

**Comment by ufladrich** [comment] 2019-03-29 07:55
Hi, sorry for hijacking this issue, but I also get the warning above:
```
[...]/cmor/pywrapper.py:764: UserWarning: Error: your data shape ((3, 256, 512)) does not match the expected variable shape ([256, 512, 3, 0])
Check your variable dimensions before caling cmor_write
  warnings.warn(msg)
```
a couple of times. The cmorisation process continues and I've not yet seen any problems with the actual output files. In fact, I have not seen an indication which variables are affected. Would be good to sort out where the warning comes from and if it is something to worry about.

**Comment by goord** [comment] 2019-03-29 08:34
Hi Uwe, I noticed those warnings too and I am working on it. They do affect mrsol in 6hrPlevPt: I get scrambled values in the cmorized file.

**Comment by goord** [comment] 2019-03-29 10:36
Ok I 'mixed' this issue with the mrsol-problem in one branch: mrsol-sdepth1.

@ufladrich can you observe the warnings with this branch?

**Comment by oloapinivad** [comment] 2019-04-04 08:27
As long as I can tell this too is solved in the most recent commit.

**Comment by treerink** [comment] 2019-04-04 09:18
Ok then I close it, please reopen if the issue is still encountered.

**Closed by treerink** 2019-04-04 09:18 UTC
Labels: release 0.9
