### ISSUE TITLE
Skipped tos 3hr by ece2cmor

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#477] opened 2019-05-29 09:05 UTC
In [435](https://github.com/EC-Earth/ece2cmor3/issues/435#issuecomment-483650979) the 3 hourly `tos` coming from NEMO is skipped for unknown reasons. First thing to check is if somewhere the 3hr or 3h labeling goes wrong. However under point 4 in [435](https://github.com/EC-Earth/ece2cmor3/issues/435#issuecomment-483650979) there are more NEMO variables skipped which need to be figured out (in other issues to come).

**Comment by treerink** [comment] 2019-05-29 14:44
Note that the `tos 3h` is correctly outputted by NEMO, so the control output files are fine. The issue seems to be that the task  `tos 3h` is not recognized.

**Comment by goord** [comment] 2019-06-06 09:47
The issue is that the cmor frequency of tos in the 3hr table is ```3hrPt```, which means instantaneous fluxes. I guess we put such data also in the 3h netcdf file (possibly together with averaged data). Ece2cmor3 was not taking such instantaneous fields into account for the ocean...

**Comment by goord** [comment] 2019-06-06 10:00
Fixed in 8dfd449e7e8b52c0d41fc418385f2037d0777420

**Closed by goord** 2019-06-06 10:00 UTC
Labels: release 1.0.x

**Comment by oloapinivad** [comment] 2019-06-12 10:39
Hi all,

there is something which puzzles me re. 3hr `tos`. 
This is an instantaneous field - not a flux -  which should be exactly as `tas`, since physically should be the same. Both are `frequency": "3hrPt"`

So why the files have different time window? `tos` ends up at the midnight (as a cumulated flux) while tas ends at the 2100 of the 31/12. You can spot this from the file names:
 
`tos_3hr_EC-Earth3_historical_r4i1p1f1_gn_185001010300-185101010000.nc`
`tas_3hr_EC-Earth3_historical_r4i1p1f1_gr_185001010000-185012312100.nc `

Is this expected?

**Comment by treerink** [comment] 2019-06-12 10:45
@oloapinivad new problem, new issue please :)

**Comment by oloapinivad** [comment] 2019-06-12 10:46
ahah ok!
