### ISSUE TITLE
Possibly wrong ocean vertical axis in cmorized data ￼

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#401] opened 2019-02-22 14:57 UTC
Hi, @goord and @treerink 

While checking the output of NEMO cmorized data, we noticed, here at BSC, that there are wrong values for lev in 3D vars, such as ua and va. For example, the result of 

"ncdump -v lev uo_Omon_EC-Earth3_historical_r2i1p1f1_gn_185001-185012.nc"

is the following output:

 lev = 0, 1.02390658855438, 2.10318994522095, 3.25130915641785, 
    4.48505258560181, 5.82523775100708, 7.29744291305542, 8.93268585205078, 
    10.767897605896, 12.8459920883179, 15.2152690887451, 17.9279232025146, 
    21.0375709533691, 24.5959873199463, 28.6496505737305, 33.2369651794434, 
    38.3871002197266, 44.1210098266602, 50.4544677734375, 57.4025650024414, 
    64.9846038818359, 73.2286987304688, 82.1755599975586, 91.8814086914062, 
    102.42017364502, 113.885238647461, 126.390930175781, 140.073974609375, 
    155.09504699707, 171.640243530273, 189.922790527344, 210.184463500977, 
    232.696975708008, 257.762878417969, 285.715789794922, 316.919860839844, 
    351.768005371094, 390.678619384766, 434.090545654297, 482.456329345703, 
    536.233215332031, 595.8720703125, 661.805236816406, 734.43212890625, 
    814.105651855469, 901.117980957031, 995.688537597656, 1097.9541015625, 
    1207.96301269531, 1325.67248535156, 1450.95043945312, 1583.58239746094, 
    1723.27978515625, 1869.69311523438, 2022.42492675781, 2181.04443359375, 
    2345.10107421875, 2514.13720703125, 2687.69946289062, 2865.34692382812, 
    3046.6591796875, 3231.24047851562, 3418.72290039062, 3608.76928710938, 
    3801.07202148438, 3995.35424804688, 4191.3671875, 4388.8896484375, 
    4587.7255859375, 4787.7021484375, 4988.66748046875, 5190.48828125, 
    5393.04931640625, 5596.2490234375, 5800 ;

We think it should start at 0.5, shouldn't it?

**Comment by goord** [comment] 2019-02-22 15:28
ece2cmor3 just takes the values from the XIOS-produced output axes, can you check
```
ncdump -v depthu <output.nc>
```
where output.nc is the 3D monthly file with the u-grid variables?

**Comment by aearamos** [comment] 2019-02-22 15:39
Hi Gijs,
The command ncdump -v depthu uo_Omon_EC-Earth3_historical_r2i1p1f1_gn_185001-185003.nc gives "ncdump: depthu: No such variable".

Here's a ncdump -h:

netcdf uo_Omon_EC-Earth3_historical_r2i1p1f1_gn_185001-185003 {
dimensions:
	time = UNLIMITED ; // (3 currently)
	lev = 75 ;
	j = 292 ;
	i = 362 ;
	bnds = 2 ;
	vertices = 4 ;
variables:
	double time(time) ;
		time:bounds = "time_bnds" ;
		time:units = "days since 1850-01-01 00:00:00" ;
		time:calendar = "gregorian" ;
		time:axis = "T" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
	double time_bnds(time, bnds) ;
	double lev(lev) ;
		lev:bounds = "lev_bnds" ;
		lev:units = "m" ;
		lev:axis = "Z" ;
		lev:positive = "down" ;
		lev:long_name = "ocean depth coordinate" ;
		lev:standard_name = "depth" ;
	double lev_bnds(lev, bnds) ;
	int j(j) ;
		j:units = "1" ;
		j:long_name = "cell index along second dimension" ;
	int i(i) ;
		i:units = "1" ;
		i:long_name = "cell index along first dimension" ;
	float latitude(j, i) ;
		latitude:standard_name = "latitude" ;
		latitude:long_name = "latitude" ;
		latitude:units = "degrees_north" ;
		latitude:missing_value = 1.e+20f ;
		latitude:_FillValue = 1.e+20f ;
		latitude:bounds = "vertices_latitude" ;
	float longitude(j, i) ;
		longitude:standard_name = "longitude" ;
		longitude:long_name = "longitude" ;
		longitude:units = "degrees_east" ;
		longitude:missing_value = 1.e+20f ;
		longitude:_FillValue = 1.e+20f ;
		longitude:bounds = "vertices_longitude" ;
	float vertices_latitude(j, i, vertices) ;
		vertices_latitude:units = "degrees_north" ;
		vertices_latitude:missing_value = 1.e+20f ;
		vertices_latitude:_FillValue = 1.e+20f ;
	float vertices_longitude(j, i, vertices) ;
		vertices_longitude:units = "degrees_east" ;
		vertices_longitude:missing_value = 1.e+20f ;
		vertices_longitude:_FillValue = 1.e+20f ;
	float uo(time, lev, j, i) ;
		uo:standard_name = "sea_water_x_velocity" ;
		uo:long_name = "Sea Water X Velocity" ;
		uo:comment = "Prognostic x-ward velocity component resolved by the model." ;
		uo:units = "m s-1" ;
		uo:original_name = "uo" ;
		uo:cell_methods = "time: mean" ;
		uo:history = "2019-02-22T15:28:00Z altered by CMOR: Reordered dimensions, original order: j i lev time." ;
		uo:missing_value = 1.e+20f ;
		uo:_FillValue = 1.e+20f ;
		uo:coordinates = "latitude longitude" ;

**Comment by goord** [comment] 2019-02-22 15:49
Hi @aearamos I mean the original model output, could you look at the vertical levels in the file produced by xios?

**Comment by aearamos** [comment] 2019-02-22 15:51
Hi Gijs, sorry.
I didn't find depthu in my file, but only olevel, which seems right:

olevel = 0.50576, 1.555855, 2.667682, 3.85628, 5.140361, 6.543034, 8.092519, 
    9.82275, 11.77368, 13.99104, 16.52532, 19.4298, 22.75762, 26.5583, 
    30.87456, 35.7402, 41.18002, 47.21189, 53.85064, 61.11284, 69.02168, 
    77.61116, 86.92943, 97.04131, 108.0303, 120, 133.0758, 147.4062, 
    163.1645, 180.5499, 199.79, 221.1412, 244.8906, 271.3564, 300.8875, 
    333.8628, 370.6885, 411.7939, 457.6256, 508.6399, 565.2923, 628.026, 
    697.2587, 773.3683, 856.679, 947.4479, 1045.854, 1151.991, 1265.861, 
    1387.377, 1516.364, 1652.568, 1795.671, 1945.296, 2101.027, 2262.422, 
    2429.025, 2600.38, 2776.039, 2955.57, 3138.565, 3324.641, 3513.446, 
    3704.657, 3897.982, 4093.159, 4289.953, 4488.155, 4687.581, 4888.07, 
    5089.479, 5291.683, 5494.575, 5698.061, 5902.058 ;

**Comment by goord** [comment] 2019-02-22 16:03
Hmm... so I guess that depth axis comes from the T-grid... This seems to be a bug in ece2cmor3.

**Comment by goord** [comment] 2019-02-22 16:13
I just checked my primavera data, I can't see the issue you're pointing out but I did find the vertical axis, it's in the W-grid. @aearamos could you post or send me the log of the cmorization job that produced that output? It seems there is something going wrong with the assignment of vertical axes to the variables...

**Comment by goord** [comment] 2019-02-22 16:33
Hi @aearamos I think I figured out what is going on: in the new CMIP6 ocean output all vertical axes are named 'olevel' right? Because of this, ece2cmor3 assumes it can 're-use' those axes for all 2D variables, which obviously is not the case.

The fix is to combine the file grid id and the axis name to a unique combination.

**Comment by aearamos** [comment] 2019-02-22 16:37
If you still want the log, here it is:

[a1rh_18500101_fc0_2_CMOROCE.20190221010405.txt](https://github.com/EC-Earth/ece2cmor3/files/2894873/a1rh_18500101_fc0_2_CMOROCE.20190221010405.txt)

**Comment by aearamos** [comment] 2019-02-26 17:18
Hi Gijs,
So, the idea is to rename the vertical levels in ece2cmor3 so they correspond to the original one and not the "olevel"? I think maybe all the 3D variables may have been affected by this.

**Comment by goord** [comment] 2019-02-27 17:10
Hi Arthur, you are right all 3D variables are affected. The problem is that the vertical levels in the XIOS output used to be named after their grid (deptu, depthv, deptht, etc.) and ece2cmor3 used this to make an administration for the vertical axes of all 3D variables, a sort of lookup table. With the new output, all vertical axes in the XIOS output are names 'olevel', which breaks that lookup table, so ece2cmor3 now thinks effectively that all 3D variables have the same vertical axis.

So how can we preserve the administration and distinguish between the vertical discretizations of NEMO? I guess we look at the file name, or maybe the long name of the olevel variable, I think that one does differ between grids?

I will create a branch this evening you can test with

**Comment by aearamos** [comment] 2019-02-27 17:25
I think both alternatives are good. Here's the long name for the grid_T_3D. If we can extract the axis_ref from nemo, then we'd get the right deths. 
    <grid id="grid_T_3D" >
      <domain domain_ref="grid_T" />
      <axis axis_ref="deptht" name="olevel" />
    </grid>

I think it's the same for the file names. We'd have to find a way to call deptht/ depthu /depthv.

I can test the cmorisation for you.

**Comment by goord** [comment] 2019-02-28 09:59
Hi @aearamos I put some changes in the olevel_fix branch, could you test with your EC-Earth output?

**Comment by aearamos** [comment] 2019-02-28 13:56
Will test it now.

**Comment by aearamos** [comment] 2019-02-28 14:19
Hi @gijs,
We had a first look and the vertical axis for the variables seem to be right and they're the same for the raw output and cmorised output. I think your fix worked.

**Comment by goord** [comment] 2019-02-28 15:21
Ok, I'll close the issue then.
Fixed in pull request #402

**Closed by goord** 2019-02-28 15:21 UTC
